name: 'allure-html-reporter-aws-s3-website'
description: 'Allure HTML Test Results with history to publish to AWS S3 Bucket'
branding:
  icon: 'layout'
  color: 'green'
inputs:
  allure_results:
    description: 'Allure test result data dir'
    required: false
    default: 'allure-results'
  allure_report:
    description: 'Allure report target dir'
    required: false
    default: 'allure-report'
  allure_history:
    description: 'Folder for allure history'
    required: false
    default: 'allure-history'
  keep_reports:
    description: 'Keep X last reports'
    required: false
    default: '20'    
  github_run_num:
    description: 'GitHub Actions build number'
    required: false
    default: ${{ github.run_number }}
  github_run_id:
    description: 'GitHub Actions run id'
    required: false
    default: ${{ github.run_id }}
  report_url:
    description: 'Use a custom URL instead of *.github.io'
    required: false
    default: ''
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install allure
      run: |

        # install java in generic
        sudo apt update && sudo apt install default-jre -y
        java -version

        # Set the release version and Allure repository URL
        RELEASE="2.24.0"
        ALLURE_REPO="https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline"

        # Download and extract Allure
        sudo apt-get install -y wget
        wget --no-verbose -O allure-${RELEASE}.tgz ${ALLURE_REPO}/${RELEASE}/allure-commandline-${RELEASE}.tgz
        tar -xf allure-${RELEASE}.tgz

        # Add Allure to the PATH
        export PATH="$PATH:$(pwd)/allure-${RELEASE}/bin"
        echo "PATH="$PATH:$(pwd)/allure-${RELEASE}/bin"" >> $GITHUB_ENV

        # Print Allure version
        allure --version
      
      shell: bash
      
    - name: Generate allure results
      run: |
        echo "Generated results"
      shell: bash

    - name: Generate allure results
      run: |
        chmod +x entrypoint.sh
      shell: bash

    - name: Upload allure results
      run: entrypoint.sh
      shell: bash
      env:
        INPUT_ALLURE_HISTORY: ${{ inputs.allure_history }}
        INPUT_ALLURE_RESULTS: ${{ inputs.allure_results }}
        INPUT_ALLURE_REPORT: ${{ inputs.allure_report }}
        INPUT_KEEP_REPORTS: ${{ inputs.keep_reports }}
        INPUT_GITHUB_RUN_NUM: ${{ inputs.github_run_num }}
        INPUT_GITHUB_RUN_ID: ${{ inputs.github_run_id }}
        INPUT_REPORT_URL: ${{ inputs.report_url }}
        INPUT_GITHUB_REPO: ${{github.repository}}
        