name: allure

on: push

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git Repo
        uses: actions/checkout@v3

      - name: allure-html-report-s3-website
        uses: avsprashant/allure-html-reporter-aws-s3-website@add-aws-profile
        with:
          report_url: http://${{ secrets.AWS_S3_BUCKET }}.s3-website-${{ secrets.AWS_REGION }}.amazonaws.com
          allure_results: allure-results
          allure_history: allure-history
          allure_report: allure-report
          keep_reports: 10
          args: --acl public-read --follow-symlinks
        env:
          AWS_S3_BUCKET: #s3 bucket name
          AWS_PROFILE: uk
          # AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          # AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ''   # optional: defaults to us-east-1
          SOURCE_DIR: 'allure-history'      # optional: defaults to entire repository
          # DEST_DIR: ${{ env.GITHUB_RUN_NUMBER }}
          
      # - name: Post the link to the report
      #   if: always()
      #   uses: Sibz/github-status-action@v1
      #   with: 
      #       authToken: ${{secrets.GITHUB_TOKEN}}
      #       context: 'Test Results Link'
      #       state: 'success'
      #       sha: ${{ github.sha }}
      #       target_url: http://${{ secrets.AWS_S3_BUCKET }}.s3-website-${{ secrets.AWS_REGION }}.amazonaws.com/index.html
